version: 2
jobs:
  conda:
    docker:
      - image: continuumio/miniconda3
    steps:
      - run: echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc
      - checkout
      - run: conda env update
      - run: cd numba && python setup.py develop
      - run: python -m unittest
workflows:
  version: 2
  test:
    jobs:
      - conda
